import {z} from 'zod'

export const collegeFormSchema = z.object({
  name: z.string().min(1),
  code: z.string().min(1),
  type: z.string(),
  university: z.string(),
  establishedYear: z.string(),
  aicteApproved: z.string(),
  naacGrade: z.string(),
  naccScore: z.string(),
  collegeCode: z.string(),
  affiliationNumber: z.string(),
  panNumber: z.string(),
  email: z.string().email(),
  phone: z.string(),
  website: z.string(),
  address: z.string(),
  logoUrl: z.string().url(),
  coverImageUrl: z.string().url(),
  themeColor: z.string(),
  studentsCount: z.string(),
  teachersCount: z.string(),
  membersCount: z.string(),
  adminsCount: z.string(),
  placementYearStart: z.string(),
  isVerified: z.string(),
  verificationStatus: z.string(),
  status: z.string(),
  createdAt: z.string(),
  createdBy: z.string(),
  updatedAt: z.string(),
  updatedBy: z.string(),
  internalMeta: z.string(),
})